config/routes.rb
Rails.application.routes.draw do
  
  mount EpiCas::Engine, at: "/"
  devise_for :users
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all
  match "/modules", to: "pages#modules", via: :all
  match "/toa", to: "toa#toa_doc", via: :all
  match "/tmr", to: "tmr#tmr_doc", via: :all
  match "/admin", to: "admin#admin_page", via: :all
  match "/admin/privileges", to: "admin#admin_privileges", via: :all
  match "/admin/modules", to: "admin#admin_modules", via: :all
  match "/admin/modules/preview", to: "admin#admin_modules_preview", via: :all
  match "/admin/modules/create", to: "admin#admin_modules_create", via: :all
  match "/module_handbook", to: "pages#module_handbook", via: :all
  match "/admin/modules/edit", to: "admin#admin_modules_edit", via: :all
  match "/admin/modules/privilege", to: "admin#admin_modules_privilege", via: :all
  match "/admin/modules/groups", to: "admin#admin_modules_groups", via: :all
  match "/admin/modules/groups/preview", to: "admin#admin_modules_groups_preview", via: :all
  match "/admin/modules/groups/add", to: "admin#admin_modules_groups_add", via: :all
  match "/admin/modules/groups/create", to: "admin#admin_modules_groups_create", via: :all
  match "/student/groups", to: "pages#student_groups_join", via: :all
  match "/feedback/matrix", to: "feedback#feedback_matrix", via: :all
  match "/feedback/review/all", to: "feedback#feedback_review_all", via: :all
  match "/feedback/review/all/save", to: "feedback#save_feedback", via: :all
  match "/feedback/review/all/approve", to: "feedback#approve_feedback", via: :all
  match "/feedback/mailmerge/edit", to: "feedback#feedback_mailmerge_edit", via: :all
  match "/problem_notes", to: "problem_notes#create", via: :all
  match "/admin/modules/preview/import_users", to: "admin#import_users_csv", via: :all
  match "/student/profile", to: "pages#student_profile", via: :all
  match "/admin/modules/groups/approve", to: "admin#approve_teams", via: :all
  match "/admin/modules/periods/edit", to: "admin#admin_modules_periods_edit", via: :all
  match "/edit/feedback/periods", to: "admin#edit_feedback_periods", via: :all
  match "/student/profile/feedback/old", to: "pages#student_profile_feedback_old", via: :all
  match "/student/profile/docs/old", to: "pages#student_profile_docs_old", via: :all
  match "/student/profile/select/module", to: "pages#student_profile_select_module", via: :all
  match "/feedback/old/show", to: "pages#feedback_old_show", via: :all
  match "/send/feedback/mailmerge", to: "admin#send_feedback_mailmerge", via: :all
  match "/remove/student/from/team", to: "admin#remove_student_from_team", via: :all
  match "/assign/solve/problem", to: "admin#assign_solve_problem", via: :all
  match "/add/individual/user", to: "admin#add_individual_user", via: :all
  match "/admin/modules/groups/docs", to: "admin#admin_modules_groups_docs", via: :all
  
  


  



  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'



  root to: "pages#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/_edited_feedback_periods.html.haml
.container-fluid.text_black.bg_none.margin_bottom_small.no_padding.special_size_2.float_left
  - for i in 1..@not_started_f_periods.length
    - start_date = @not_started_f_periods[i-1].start_date.strftime("%Y-%m-%dT%H:%M")
    - end_date = @not_started_f_periods[i-1].end_date.strftime("%Y-%m-%dT%H:%M")
    .container-fluid.text_black.bg_none.no_padding.margin_bottom_small
      %p.margin_none
        %strong#time_name_1
          Period #{i}
      .row.margin_none.no_padding
        .col.margin_none.no_padding.padding_right_small
          - # Time period start date
          .container-fluid.text_black.bg_none.no_padding.margin_bottom_small
            %label{id: "start_time_label_" + "#{i.to_s}", for: "start_time_#{i}_time"} Start Date: 
            %input.float_right{id: "start_time_" + "#{i.to_s}", name: "start_time_#{i}", type: "datetime-local", value: "#{start_date}", readonly: true}
            //%button.add.btn.btn-primary.button_topics{type: "button", onclick: "addPeriod()"}Add period
          
          - # Time period end date
          .container-fluid.text_black.bg_none.no_padding.margin_bottom_small
            %label{id: "end_time_label_" + "#{i.to_s}",for: "end_time_#{i}_time"} End Date:   
            %input.float_right{id: "end_time_" + "#{i.to_s}", name: "end_time_#{i}", type: "datetime-local", value: "#{end_date}", readonly: true}
        
          %hr.special_line.margin_none
      
        .col.margin_none.no_padding
          .container-fluid.text_black.bg_none.no_padding.margin_bottom_small
            %button.add.btn.btn-primary.button_topics.float_left{type: "button",id: "remove_period_button_" + "#{i}", value: "#{@not_started_f_periods[i-1].id}"}
              Remove period
              %strong.text_begone
              
          -# .container-fluid.text_black.bg_none.no_padding.margin_bottom_small
          -#   %button.add.btn.btn-primary.button_topics.float_left{type: "button", onclick: "addPeriod()"}
          -#     %strong.text_begone
          -#       ya
          -#     Add period
          -#     %strong.text_begone
          -#       a2

:javascript
  edit_feedback_periods(#{@not_started_f_periods.length});
  myAlertTopEditableSuccess("Period removed successfully!");

app/views/admin/_module_users_table.html.haml
- if @current_module_users.length <= 0
  .container.no_results
    %h.center_element.bigger.text_black No users match your search
- else
  .container-fluid.bg_none.overflow_style.scroll_down.no_padding.table_div
    %table.table.table-hover.table-dark
      %thead
        %tr.stick_top
          %th.black_text{:colspan => "1", :style => "width: 5%;"} #
          %th.black_text{:colspan => "1", :style => "width: 30%;"} Name
          %th.black_text.center_element{:colspan => "1", :style => "width: 10%;"} Username
          %th.black_text.center_element{:colspan => "1", :style => "width: 20%;"} Email
          %th.black_text.center_element{:colspan => "1", :style => "width: 15%;"} Role
          %th.black_text.center_element{:colspan => "4", :style => "width: 20%;"} Action 
      %tbody
        - @current_module_users.to_a.each_with_index do |user, index|
          - if user[:givenname] == nil  
            - user[:givenname] = ""
          - if user[:sn] == nil 
            - user[:sn] = ""
          - whole_name = user[:givenname] + " " + user[:sn]
          - user_privilege = User.get_module_privilege(params[:module_id], user[:id])
          - if user_privilege.include?("teaching_assistant")
            - user_privilege = "Teaching Assistant"
          - elsif user_privilege.include?("module_leader")
            - user_privilege = "Module Leader"
          - elsif user_privilege.include?("student")
            - user_privilege = "Student"
          %tr.small.hover_color
            %td{:colspan => "1", :style => "width: 5%;"} #{index+1}
            %td{:colspan => "1", :style => "width: 30%;"} #{whole_name}
            %td.center_element{:colspan => "1", :style => "width: 10%;"} #{user[:username]}
            %td.center_element{:colspan => "1", :style => "width: 20%;"} #{user[:email]}
            %td.center_element{:colspan => "1", :style => "width: 15%;"} #{user_privilege}
            %td.center_element{:colspan => "1", :style => "width: 20%;"} 
              - if can? :manage, :admin_modules_privilege
                %button{onclick: "popupCenter({url: '/admin/modules/privilege?module_id=#{params[:module_id]}&user_id=#{user[:id]}', title: 'Change Privilege', w: 650, h: 500}); ", type: "submit", name: "privilege_button",  class: "btn btn-primary action_buttons justify-content-center small", id:"submit_choice"}Change Privilege

:javascript
  myAlertTopEditableSuccess("Students imported successfully!");
  no_file_selected();
  add_wizard_toast("You just added users to this module!", 
                   "The next step we suggest is to create teams and setup feedback periods for this module.", 
                   "/admin/modules/groups/create?module_id=" + #{params[:module_id].to_s});

app/views/admin/_problem_assigned.html.haml
- if @problem_object.status != "solved"
  Problem #{@problem_number.to_i+1} - Assigned to #{@assigned_to}
- else
  Problem #{@problem_number.to_i+1}

- if @problem_object.status == "unsolved"
  %span.dot_red.float_right
- elsif @problem_object.status == "assigned"
  %span.dot_yellow.float_right
- elsif @problem_object.status == "solved"
  %span.dot_green.float_right

- if @solve_button.nil?
  :javascript
    myAlertTopEditableSuccess("Problem has been assigned to: " + '#{@problem_object.assigned_to}')

app/views/admin/_problem_solved.html.haml
%p Solved by: #{@solved_by}
%p Solved on: #{@solved_on}

- if @assign_button.nil?
  :javascript
    myAlertTopEditableSuccess("Problem has been marked as solved!")

app/views/admin/_team_members.html.haml
- current_team_users = @team_members
- if current_team_users.length <= 0
  .container.no_results
    %h.center_element.bigger.text_black No students in the team
- else
  .container-fluid.bg_none.overflow_style.scroll_down.no_padding.table_div
    %table.table.table-hover.table-dark 
      %tbody
        %tr.medium
          %th.black_text{:colspan => "1", :style => "width: 5%;"} #
          %th.black_text{:colspan => "1", :style => "width: 30%;"} Name
          %th.black_text.center_element{:colspan => "1", :style => "width: 10%;"} Username
          %th.black_text.center_element{:colspan => "1", :style => "width: 20%;"} Email
          %th.black_text.center_element{:colspan => "1", :style => "width: 15%;"} Last Login
          %th.black_text.center_element{:colspan => "4", :style => "width: 20%;"} Action
          - current_team_users.to_a.each_with_index do |user, index|
            - if user[:givenname] == nil  
              - user[:givenname] = ""
            - if user[:sn] == nil 
              - user[:sn] = ""
            - whole_name = user[:givenname] + " " + user[:sn]
            %tr.small.hover_color
              - form_id = "remove_student_form_" + user[:id].to_s
              = form_tag remove_student_from_team_path(module_id: @module_id), :method => :post, :id => form_id, remote: true do
                %input#user_remove_id{name: "student_remove_id", type: "hidden", value: user[:id], form: form_id}
                %input#team_id{name: "team_id", type: "hidden", value: @team_id, form: form_id}
                %input#team_number{name: "team_number", type: "hidden", value: @team_number, form: form_id}
                - last_login = user[:last_sign_in_at]
                - if last_login.nil?
                  - last_login = ""
                - else
                  - last_login = user[:last_sign_in_at].strftime("%d/%m/%Y")
                %td{:colspan => "1", :style => "width: 5%;"} #{index+1}
                %td{:colspan => "1", :style => "width: 30%;"} #{whole_name}
                %td.center_element{:colspan => "1", :style => "width: 10%;"} #{user[:username]}
                %td.center_element{:colspan => "1", :style => "width: 20%;"} #{user[:email]}
                %td.center_element{:colspan => "1", :style => "width: 15%;"} #{last_login}
                %td.center_element{:colspan => "1", :style => "width: 20%;"} 
                  - if can? :manage, :admin_modules_groups_add
                    %button{type: "submit", name: "remove_student_button", form: form_id, class: "btn btn-primary action_buttons justify-content-center small", id:"remove_user_button", value: "remove_student"}Remove Student

:javascript
  myAlertTopEditableSuccess("Student removed from team successfully!");

app/views/admin/admin_modules_groups_add.html.haml
- # View for adding students into teams
- # Authors: Anton Minkov && Laney Deveson
- # Date: 13/04/2021

- content_for :title, "Group Add Student"

.container.body_whole_custom
  .container-fluid.bg_none.text_black.margin_top.bigger
    - team_topic = "-"
    - if @selected_group_team.topic != "none"
      - team_topic = "- " + @selected_group_team.topic + " -"
    #{@selected_group_team.name} #{team_topic}
    #{@current_team_size}/#{@max_team_size}
    %a.button.float_right.no_padding.btn.btn-primary.agreement_buttons.justify-content-center.button_go_back_1.medium.button_small{:href => admin_modules_groups_path(module_id: params[:module_id]), type: "button"} Go Back
    %hr.group_line
    
    - # Search form
    .container-fluid.bg_none.no_padding.bg_border.margin_bottom_small.bg_white.no_border
      = simple_form_for :search_form do |f|
        .container-fluid.bg_none.no_padding
          = image_tag('search_logo.jpg', alt: 'Search Users', class: 'search_logo margin_none')
        .container-fluid.bg_none.row.no_padding.margin_bottom_none  
          = f.input :form_module_id, :as => :hidden, :input_html => {:id => "form_module_id", :value => params[:module_id] }
          = f.input :form_team_id, :as => :hidden, :input_html => {:id => "form_team_id", :value => params[:team_id] }
          .container.col-xs-9.col-sm-5.no_padding_right.no_padding_left
            = f.input :search_input, as: :string, label: false , required: false
          .container.col-xs-9.col-sm-7.no_padding_left
            = f.button :submit, "Search", name:"search_button", class: "btn btn-primary agreement_buttons justify-content-center button_search_3 float_left no_padding bigger", id:"search_choice"

    - # Table of students in the module but NOT in any team
    .container-fluid.bg_none.bg_border.no_padding.margin_bottom_small
      - if @users_in_module_but_not_in_team.length <= 0
        .container.no_results
          %h.center_element.bigger.text_black No users match your search
      - else
        .container-fluid.bg_none.overflow_style.scroll_down.no_padding.table_div
          %table.table.table-hover.table-dark 
            %tbody
              %tr.medium
                %th.black_text{:colspan => "1", :style => "width: 5%;"} #
                %th.black_text{:colspan => "1", :style => "width: 30%;"} Name
                %th.black_text.center_element{:colspan => "1", :style => "width: 10%;"} Username
                %th.black_text.center_element{:colspan => "1", :style => "width: 20%;"} Email
                %th.black_text.center_element{:colspan => "1", :style => "width: 15%;"} Last Login
                %th.black_text.center_element{:colspan => "4", :style => "width: 20%;"} Action
                - @users_in_module_but_not_in_team.to_a.each_with_index do |user, index|
                  - if user[:givenname] == nil  
                    - user[:givenname] = ""
                  - if user[:sn] == nil 
                    - user[:sn] = ""
                  - whole_name = user[:givenname] + " " + user[:sn]
                  %tr.small.hover_color
                    = form_tag admin_modules_groups_add_path(module_id: params['module_id'], team_id: params['team_id']), :method => :post, :id => 'add_student_form' do
                      %input#user_remove_id{name: "student_add_id", type: "hidden", value: user[:id]}
                      - last_login = user[:last_sign_in_at]
                      - if last_login.nil?
                        - last_login = ""
                      - else
                        - last_login = user[:last_sign_in_at].strftime("%d/%m/%Y")
                      %td{:colspan => "1", :style => "width: 5%;"} #{index+1}
                      %td{:colspan => "1", :style => "width: 30%;"} #{whole_name}
                      %td.center_element{:colspan => "1", :style => "width: 10%;"} #{user[:username]}
                      %td.center_element{:colspan => "1", :style => "width: 20%;"} #{user[:email]}
                      %td.center_element{:colspan => "1", :style => "width: 15%;"} #{last_login}
                      %td.center_element{:colspan => "1", :style => "width: 20%;"} 
                        %button{type: "submit", name: "add_student_button",  class: "btn btn-primary action_buttons justify-content-center small", id:"submit_choice", value: "add_student"}Add Student

app/views/admin/admin_modules_groups_docs.html.haml
- # View for previous documents
- # Authors: Anton Minkov && Laney Deveson
- # Date: 16/05/2021

- content_for :title, @team.name + " - Previous Documents"

.container.body_whole_custom
  .container-fluid.text_black.bg_none.margin_top
    .container-fluid.bg_none.text_black
      .container-fluid.bg_none.text_black.text_center
        %h.bigger.width_100
          Documents for #{@team.name}
        %hr.group_line
      .container-fluid.bg_none.text_black.margin_top.bigger
        %p.small
          %strong
            Team Operating Agreement Download 
        %hr
        %ul
          %li
            - # Display the download TOP option
            %p.small
              - if @team.document.attached? && @team.toa_status == "finished"
                %i
                  = link_to 'Team Operating Agreement - ' + @team.document.created_at.strftime("%d/%m/%Y").to_s, rails_blob_path(@team.document, disposition: "attachment")
              - else
                %i
                  No Team Operating Agreement recorded for this team.
        %hr
        %p.small
          %strong
            Team Meeting Records Download 
        %hr
        %ul
          - if @tmrs.length == 0
            %li
              %p.small
                %i
                  No Team Meeting Records saved for this team.
                %hr
          - for y in 0...@tmrs.length
            %li
              - # Display the download TMR option
              %p.small
                %i
                  = link_to 'Team Meeting Record - ' + @tmrs[y].tmr_doc.created_at.strftime("%d/%m/%Y").to_s, rails_blob_path(@tmrs[y].tmr_doc, disposition: "attachment")
              - if y != 7
                %hr

app/views/admin/admin_modules_privilege.html.haml
- # View for module privileges
- # Authors: Anton Minkov && Laney Deveson
- # Date: 06/04/2021

- content_for :title, "Module Privileges"

.container.body_whole_custom_4
  - # Display possible privileges
  .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top
    %h.float_left.bigger
      Change privilege for user: #{User.get_user_info_by_id(params['user_id']).givenname} #{User.get_user_info_by_id(params['user_id']).sn}
  %hr.group_line.special_margin_top
  = form_tag admin_modules_privilege_path(module_id: params['module_id'], user_id: params['user_id']), :method => :post, :id => 'privilege_form' do
    .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top
      .btn-group.btn-group-toggle{"data-toggle" => "buttons"}
        %label.btn.btn-secondary.active.bg_purple
          %input#option1{name: "options1", type: "radio", onclick: "disable_toogle();disable_opt_23();"}
          Student
        %label.btn.btn-secondary.bg_purple
          %input#option2{name: "options2", type: "radio", onclick: "enable_toogle();disable_opt_13();"}
          Teaching Assistant
        %label.btn.btn-secondary.bg_purple
          %input#option3{name: "options3", type: "radio", onclick: "disable_toogle();disable_opt_12();"}
          Module Leader

    - # Display teaching assinstant additional privileges
    .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top_px_medium
      
      - # Send feedback to students
      .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top_px_small
        %label.switch
          %input#privilege_1{type: "checkbox", name: "privilege_1"}
          %span.slider.round#slider1
        %p.margin_left#privilege_1_text Send mail feedback to students

      - # Deal with problems
      .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top_px_small
        %label.switch
          %input#privilege_2{type: "checkbox", name: "privilege_2"}
          %span.slider.round#slider2
        %p.margin_left#privilege_2_text See teams that have flagged problems

      - # Edit/Clone module
      .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top_px_small
        %label.switch
          %input#privilege_3{type: "checkbox", name: "privilege_3"}
          %span.slider.round#slider3
        %p.margin_left#privilege_3_text Enable module edit/clone

      - # Manage student teams
      .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top_px_small
        %label.switch
          %input#privilege_4{type: "checkbox", name: "privilege_4"}
          %span.slider.round#slider4
        %p.margin_left#privilege_4_text Managing student teams

    - if @saved_privilege[0,18] != "teaching_assistant"
      - # Disables privileges upon load if chosen user is not teaching assistant
      :javascript
        document.getElementById("privilege_1").disabled = true;
        document.getElementById("privilege_2").disabled = true;
        document.getElementById("privilege_3").disabled = true;
        document.getElementById("privilege_4").disabled = true;
        document.getElementById("privilege_1_text").style.color = "gray";
        document.getElementById("privilege_2_text").style.color = "gray";
        document.getElementById("privilege_3_text").style.color = "gray";
        document.getElementById("privilege_4_text").style.color = "gray";
        document.getElementById("slider1").style.backgroundColor = "gray";
        document.getElementById("slider2").style.backgroundColor = "gray";
        document.getElementById("slider3").style.backgroundColor = "gray";
        document.getElementById("slider4").style.backgroundColor = "gray";

    - # Submit form
    %hr.group_line.special_margin_top
    .container-fluid.bg_none.row.no_padding.margin_bottom_none.text_black.special_margin_top_px_medium
      %button.btn.btn-primary.agreement_buttons.justify-content-center.button_change_privilege.float_left.medium{type: "submit", value: "Save", name: "save_button", id: "save_button"} Save
      %button.btn.btn-primary.agreement_buttons.justify-content-center.button_change_privilege.float_left.medium.margin_left_small{type: "button", value: "Close", name: "close_button", onclick: "window.close()"} Close Window

:javascript
  set_checked_option('#{@saved_privilege}');
  set_switches('#{@saved_privilege}');
  quit_after_save('#{@close_window}');

app/views/admin/admin_page.html.haml
- # View for admin page
- # Authors: Anton Minkov && Laney Deveson
- # Date: 04/04/2021

- content_for :title, "Admin"

.container.body_whole.bg_none
  = simple_form_for :admin_choice do |f|
    - if can? :manage, :admin_privileges
      .container-fluid.bg_none_margin
        = f.button :submit, "Manage System Privileges", name:"manage_privileges", class: "btn btn-primary choose_buttons justify-content-left button_gradient bigger transit_timer", id:"submit_choice"
    .container-fluid.bg_none_margin
      = f.button :submit, "Manage Modules", name:"manage_modules", class: "btn btn-primary choose_buttons justify-content-left button_gradient bigger transit_timer", id:"submit_choice"

app/views/admin/admin_privileges.html.haml
- # View for system privileges
- # Authors: Anton Minkov && Laney Deveson
- # Date: 05/04/2021

- content_for :title, "Admin Privileges"
  

.container.body_whole_custom_transparent
  
  - # Search form for system users
  .container-fluid.bg_none.no_padding.bg_border.margin_bottom_small.bg_white
    = simple_form_for :search_form do |f|
      .container-fluid.bg_none.text_black.center_text.special_margin_top
        %a.button.add.btn.btn-primary.button_topics.float_right.medium{:href => admin_path(module_id: params['module_id']), type: "button"} Go back
      .container-fluid.bg_none.no_padding
        = image_tag('search_logo.jpg', alt: 'Search Modules', class: 'search_logo_special')
      .container-fluid.bg_none.row.no_padding
        .container.col-xs-14.col-sm-9.no_padding_right
          = f.input :search_input, as: :string, label: false , required: false
        .container.col-xs-4.col-sm-3.no_padding_left
          = f.button :submit, "Search", name:"search_button", class: "btn btn-primary agreement_buttons justify-content-center button_search_special float_right", id:"submit_choice", "data-disable-with" => "Submitting.."

  - # Table of all system users with the option to change system privilge (suspend/admin)
  .container-fluid.bg_none.bg_border.no_padding
    - if @users_list.length <= 0
      .container.no_results
        %h.center_element.bigger.text_black No users match your search
    - else
      .container-fluid.bg_none.overflow_style.scroll_down.no_padding.table_div
        %table.table.table-hover.table-dark
          %thead 
            %tr 
              %th.black_text{:colspan => "1", :style => "width: 5%;"} #
              %th.black_text{:colspan => "1", :style => "width: 25%;"} Name
              %th.black_text.center_element{:colspan => "1", :style => "width: 10%;"} Username
              %th.black_text.center_element{:colspan => "1", :style => "width: 10%;"} Suspended
              %th.black_text.center_element{:colspan => "1", :style => "width: 10%;"} Admin
              %th.black_text.center_element{:colspan => "4", :style => "width: 40%;"} Actions
          %tbody
            = simple_form_for :privilege_form, :id => 'privilege_form' do |f|
              = f.input :form_username, :as => :hidden, :input_html => {:id => "form_username", :value => "" }
              - @users_list.to_a.each_with_index do |user, index|
                - if user[:givenname] == nil  
                  - user[:givenname] = ""
                - if user[:sn] == nil 
                  - user[:sn] = ""
                - whole_name = user[:givenname] + " " + user[:sn]
                %tr.small.hover_color
                  - suspendedBool = ""
                  - adminBool = ""
                  - if user[:suspended] == true 
                    - suspendedBool = "Yes"
                  - else  
                    - suspendedBool = "No"
                  - if user[:admin] == true 
                    - adminBool = "Yes"
                  - else  
                    - adminBool = "No"
                  %td{:colspan => "1", :style => "width: 5%;"} #{index+1}
                  %td{:colspan => "1", :style => "width: 25%;"} #{whole_name}
                  %td.center_element{:colspan => "1", :style => "width: 10%;"} #{user[:username]}
                  %td.center_element{:colspan => "1", :style => "width: 10%;"} #{suspendedBool}
                  %td.center_element{:colspan => "1", :style => "width: 10%;"} #{adminBool}
                  %td{:colspan => "1", :style => "width: 10%;"} 
                    = f.button :submit, "Suspend", name:"suspend_button", class: "btn btn-primary action_buttons justify-content-center small", id:"submit_choice", "data-disable-with" => false, onclick: "userFunction('#{user[:username]}')"
                  %td{:colspan => "1", :style => "width: 10%;"}
                    = f.button :submit, "Unsuspend", name:"unsuspend_button", class: "btn btn-primary action_buttons justify-content-center small", id:"submit_choice", "data-disable-with" => false, onclick: "userFunction('#{user[:username]}')"
                  %td{:colspan => "1", :style => "width: 10%;"} 
                    = f.button :submit, "Make Admin", name:"make_admin_button", class: "btn btn-primary action_buttons justify-content-center small", id:"submit_choice", "data-disable-with" => false, onclick: "userFunction('#{user[:username]}')"
                  %td{:colspan => "1", :style => "width: 10%;"} 
                    = f.button :submit, "Remove Admin", name:"remove_admin_button", class: "btn btn-primary action_buttons justify-content-center small", id:"submit_choice", "data-disable-with" => false, onclick: "userFunction('#{user[:username]}')"

app/views/admin/assign_solve_problem.js.erb
$("<%= @problem_assigned_div %>").html("<%= escape_javascript(render partial: 'admin/problem_assigned') %>");

$("<%= @problem_solved_div %>").html("<%= escape_javascript(render partial: 'admin/problem_solved') %>");

$("<%= @team_header_div %>").html("<%= escape_javascript(render partial: 'admin/team_header') %>");

<% if @problem_object.status == "solved" %>
  $("<%= @assign_solve_buttons_div %>").empty();
<% end %>

app/views/admin/import_users_csv.js.erb
$("<%= @div_name %>").html("<%= escape_javascript(render partial: 'admin/module_users_table') %>");