config/routes.rb
Rails.application.routes.draw do
  
  mount EpiCas::Engine, at: "/"
  devise_for :users
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all
  match "/modules", to: "pages#modules", via: :all
  match "/toa", to: "toa#toa_doc", via: :all
  match "/tmr", to: "tmr#tmr_doc", via: :all
  match "/admin", to: "admin#admin_page", via: :all
  match "/admin/privileges", to: "admin#admin_privileges", via: :all
  match "/admin/modules", to: "admin#admin_modules", via: :all
  match "/admin/modules/preview", to: "admin#admin_modules_preview", via: :all
  match "/admin/modules/create", to: "admin#admin_modules_create", via: :all
  match "/module_handbook", to: "pages#module_handbook", via: :all
  match "/admin/modules/edit", to: "admin#admin_modules_edit", via: :all
  match "/admin/modules/privilege", to: "admin#admin_modules_privilege", via: :all
  match "/admin/modules/groups", to: "admin#admin_modules_groups", via: :all
  match "/admin/modules/groups/preview", to: "admin#admin_modules_groups_preview", via: :all
  match "/admin/modules/groups/add", to: "admin#admin_modules_groups_add", via: :all
  match "/admin/modules/groups/create", to: "admin#admin_modules_groups_create", via: :all
  match "/student/groups", to: "pages#student_groups_join", via: :all
  match "/feedback/matrix", to: "feedback#feedback_matrix", via: :all
  match "/feedback/review/all", to: "feedback#feedback_review_all", via: :all
  match "/feedback/review/all/save", to: "feedback#save_feedback", via: :all
  match "/feedback/review/all/approve", to: "feedback#approve_feedback", via: :all
  match "/feedback/mailmerge/edit", to: "feedback#feedback_mailmerge_edit", via: :all
  match "/problem_notes", to: "problem_notes#create", via: :all
  match "/admin/modules/preview/import_users", to: "admin#import_users_csv", via: :all
  match "/student/profile", to: "pages#student_profile", via: :all
  match "/admin/modules/groups/approve", to: "admin#approve_teams", via: :all
  match "/admin/modules/periods/edit", to: "admin#admin_modules_periods_edit", via: :all
  match "/edit/feedback/periods", to: "admin#edit_feedback_periods", via: :all
  match "/student/profile/feedback/old", to: "pages#student_profile_feedback_old", via: :all
  match "/student/profile/docs/old", to: "pages#student_profile_docs_old", via: :all
  match "/student/profile/select/module", to: "pages#student_profile_select_module", via: :all
  match "/feedback/old/show", to: "pages#feedback_old_show", via: :all
  match "/send/feedback/mailmerge", to: "admin#send_feedback_mailmerge", via: :all
  match "/remove/student/from/team", to: "admin#remove_student_from_team", via: :all
  match "/assign/solve/problem", to: "admin#assign_solve_problem", via: :all
  match "/add/individual/user", to: "admin#add_individual_user", via: :all
  match "/admin/modules/groups/docs", to: "admin#admin_modules_groups_docs", via: :all
  
  


  



  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'



  root to: "pages#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/feedback_controller.rb
#-----------------------------------------------------------------------
# Controller related to views for giving/receiving feedback by students
#-----------------------------------------------------------------------
# Authors: Dominik Laszczyk/ Ling Lai
# Date: 23/04/2021
#-----------------------------------------------------------------------

class FeedbackController < ApplicationController

  #called to change the current ability(used for cancancan)
  def current_ability(module_privilege = "student")
    @current_ability ||= Ability.new(current_user, module_privilege)
  end

  #action used for saving/dispalying data to the feedback matrix
  def feedback_matrix
    #getting ids of module and team
    @module_id = params['module_id']
    @team_id = params['team_id']
    @feedback_date_id = params['feedback_date_id']

    #get students that the current user has to give feedback on
    @in_team_without_current_user = User.joins(:teams)
                                        .where("teams.id = ? AND 
                                                users.id NOT IN (?)",
                                                @team_id,
                                                current_user.id
                                                )
    
    #check if feedback is completed and submitted 
    @is_feedback_completed = PeerFeedback.check_feedback_completion(@in_team_without_current_user, current_user.username, @feedback_date_id)

    if @is_feedback_completed
      render "errors/error_403"
      return
    end

    @feedback_dates = FeedbackDate.get_closest_date(Time.now, @module_id)

    @module_info = ListModule.find(@module_id)

    #backup selected values from feedback matrix(set as temp_selected)
    for i in 1..@in_team_without_current_user.length
      attendance = PeerFeedback.feedback_to_int(params['attendance_' + i.to_s])
      attitude = PeerFeedback.feedback_to_int(params['attitude_' + i.to_s])
      qac = PeerFeedback.feedback_to_int(params['qac_' + i.to_s])
      communication = PeerFeedback.feedback_to_int(params['communication_' + i.to_s])
      collaboration = PeerFeedback.feedback_to_int(params['collaboration_' + i.to_s])
      leadership = PeerFeedback.feedback_to_int(params['leadership_' + i.to_s])
      ethics = PeerFeedback.feedback_to_int(params['ethics_' + i.to_s])
      appreciate = params['appreciate_note_' + i.to_s]
      request = params['request_note_' + i.to_s]

      current_feedback = PeerFeedback.find_or_create_by(created_by: current_user.username,
                                                        created_for: @in_team_without_current_user[i-1].username,
                                                        feedback_date_id: @feedback_date_id)

      if attendance    != nil then current_feedback.update(attendance: attendance) end
      if attitude      != nil then current_feedback.update(attitude: attitude) end
      if qac           != nil then current_feedback.update(qac: qac) end
      if communication != nil then current_feedback.update(communication: communication) end
      if collaboration != nil then current_feedback.update(collaboration: collaboration) end
      if leadership    != nil then current_feedback.update(leadership: leadership) end
      if ethics        != nil then current_feedback.update(ethics: ethics) end
      if appreciate    != nil then current_feedback.update(appreciate: appreciate) end
      if request       != nil then current_feedback.update(request: request) end
      if appreciate    != nil then current_feedback.update(appreciate_edited: appreciate) end
      if request       != nil then current_feedback.update(request_edited: request) end
    end

    # final submission of feedback
    if params['submit_feedback_button'] == "submit_feedback"
      feedback_completion = true

      @in_team_without_current_user.each do |student|
        current_feedback = PeerFeedback.get_feedback_for_user(current_user.username, student.username, @feedback_date_id)
        current_feedback_array = current_feedback.pluck(:attendance, :attitude, :qac, :communication, :collaboration, :leadership, :ethics)[0]
        if current_feedback_array.all? {|i| i.is_a?(Integer) } == false
          feedback_completion = false
          break
        end

        #checking if appreciate/request fields are not empty for level 5 modules
        if @module_info.level == 5
          if current_feedback.first.appreciate.nil? || current_feedback.first.appreciate.length < 1
            feedback_completion = false
            break
          end

          if current_feedback.first.request.nil? || current_feedback.first.request.length < 1
            feedback_completion = false
            break
          end
        end


      end

      if feedback_completion
        @in_team_without_current_user.each do |student|
          feedback_finished = PeerFeedback.get_feedback_for_user(current_user.username, student.username, @feedback_date_id)
          feedback_finished.update(status: "finished")
        end
      else
        #popup some fields for feedback missing
      end

    end
  end

  #action used for reviewing feedback(for module leader or ta with permission to do so)
  def feedback_review_all
    @module_id = params['module_id']
    
    #latest finished feedback period for this module
    @last_finished_period = FeedbackDate.get_last_finished_period(Time.now, @module_id)

    #teams in this module, that are connected to the latest finished feedback period
    @teams_in_module = Team.joins(:feedback_dates)
                           .where("teams.list_module_id = ? AND 
                                   feedback_dates.id = ?", 
                                   @module_id,
                                   @last_finished_period.id)
    
    #rendering errors when no previous feedback period
    #(shouldnt happen, because in this case access to this page is disabled)
    if @last_finished_period.nil? 
      render "errors/error_500"
    elsif @last_finished_period.feedback_status == "approved"
      render "errors/error_500"
    else
      render layout: 'extra_wide'
    end
  end

  #saving feedback onchange(for module leader or ta with permission to do so)
  def save_feedback
    appreciate = params['appreciate']
    request = params['request']
    peer_feedback_id = params['peer_feedback_id']

    if appreciate != nil
      PeerFeedback.find(peer_feedback_id.to_i).update(appreciate_edited: appreciate)
    elsif request != nil
      PeerFeedback.find(peer_feedback_id.to_i).update(request_edited: request)
    end

  end

  #approving feedback for the whole feedback period(for module leader or ta with permission to do so)
  def approve_feedback
    module_id = params['module_id']
    feedback_date_id = params['feedback_date_id']

    #changing stauts to approved when approve button clicked
    if params['approve'] != nil
      FeedbackDate.find(feedback_date_id.to_i).update(feedback_status: "approved")
    end

    #redirecting back to the module page
    respond_to do |format|
      format.js { render js: "window.location = '/admin/modules/preview?module_id=#{module_id}'" }
    end
    
  end

  #action for editing the mailmerge message(only module leader and admin)
  def feedback_mailmerge_edit
    module_id = params['module_id']

    #checking if the current user has access to this page
    current_ability(User.get_module_privilege(module_id, current_user.id))
    authorize! :manage, :feedback_mailmerge_edit

    @module_info = ListModule.find(module_id.to_i)

    #if save button clicked, saving and dispaying alert
    if params['save_message'] == "save" 
      @module_info.update(mailmerge_message: params['message'])

      respond_to do |format|
        format.js { render :js => "myAlertTopSuccess();" }
      end
    end
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/feedback_mailmerge_edit.html.haml
- # View for mailmerge edit page
- # Authors: Anton Minkov && Laney Deveson
- # Date: 29/04/2021

- content_for :title, "Mailmerge Edit"

- custom_placeholder = "Some placeholder text that the module leader can type/edit. It only affects the current module. To change other parts of the text, please contact the department administration"

%form{id: "save_mailmerge", name: "save_mailmerge"}
  %input{id: "module_id", name: "module_id", type: "hidden", value: params['module_id']}
  .container.body_whole_custom
    - # Replicate template provided by client - simple text, easy to edit
    - # Set at department level
    .container-fluid.bg_none.no_padding.text_black.center_text.special_margin_top
      %a.button.add.btn.btn-primary.button_topics.float_right.medium{:href => admin_modules_preview_path(module_id: params['module_id']), type: "button"} Go back
    .container-fluid.bg_none.no_padding.text_black.center_text
      %h5.bigger Edit Mail Merge Content
      %h5.medium Software Hut
    %hr.group_line
    .container-fluid.bg_none.no_padding.text_black
      %p.small Dear {{First name}},
      
      %p.small Please see below your peer feedback for [TYPE MODULE NUMBER/NAME HERE] for Week [INSERT WEEK NO]. 
      
      %p.small 
        Your team rated you across seven teamworking values, using the Department of Mechanical Engineering's Peer Evaluation Matrix. You can find this matrix here: 
        %a{href: "https://tinyurl.com/TUoS-MEC-PFM1"} Peer Feedback Matrix

      %p.small We encourage you to take the time to reflect on this feedback and to think about your strengths as a team member, and which areas you might want to improve.
      
      - # Custom text set by the module leader
      .form-group.margin_bottom_small_override
        %textarea.form-control.medium{rows: "10", name: "custom_feedback_text", id: "custom_feedback_text"}
          #{@module_info.mailmerge_message}
      %p.small
        Best wishes,
        %br
          [SIGN OFF HERE]
    
    %hr.group_line

    .container-fluid.bg_none.no_padding.text_black
      %p.medium Peer Feedback for {{First name}} {{Last name}} for Week [TYPE WEEK NO]
      
      %p.small
        Attendance and Punctuality
        %br
          {{Evaluation [Attendance and punctuality]}}
      
      %p.small
        Attitude and Commitment
        %br
          {{Evaluation [Attitude and commitment]}}
      
      %p.small
        Quality, accuracy and completeness
        %br
          {{Evaluation [Quality, accuracy and completeness]}}

      %p.small
        Communication
        %br
          {{Evaluation [Communication]}}

      %p.small
        Collaboration
        %br
          {{Evaluation [Collaboration]}}

      %p.small
        Leadership
        %br
          {{Evaluation [Leadership]}}

      %p.small
        Professionalism and ethics
        %br
          {{Evaluation [Professionalism and ethics]}}
    

    - # Additional feedback depending on level
    - if @module_info.level == 5
      %hr.group_line
      .container-fluid.bg_none.no_padding.text_black
        %p.medium PEER COMMENTS

        %p.small
          Things I appreciate about this group member
          %br
            {{Things I appreciate about this group member}}
      
        %p.small
          Things I request from this group member
          %br
            {{Things I request from this group member}}
      %hr.group_line

    .container-fluid.bg_none.no_padding.text_black.margin_bottom_small
      %button.add.btn.btn-primary.button_topics.medium{type: "button", name: "save_mailmerge_button", id: "save_mailmerge_button", value: "Save"} Save Changes
      
:javascript
  save_mailmerge_message();

- # Alerts
.myAlert-top-success.alert.alert-success
  %strong Changes saved successfully!